### ISSUE TITLE
Deployment issue cannot find sourcecontroltoken

### ISSUE THREAD

**Issue by bjonescts** [KelvinTegelaar/CIPP#1133] opened 2022-09-26 18:56 UTC
### Description

Running into this error whenever I try to deploy with the "Click to Deploy' button:
{
  "code": "DeploymentFailed",
  "message": "At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.",
  "details": [
    {
      "message": "Cannot find SourceControlToken with name GitHub."
    }
  ]
}

I've re-generated my token several times and even deleted and remade it.  I must be missing something simple.

### Environment data

```PowerShell
Azure
```

**Comment by bjonescts** [comment] 2022-09-26 19:03
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment] 2022-09-26 19:05
Which deployment button are you using?

**Comment by bjonescts** [comment] 2022-09-26 19:07
I have tried them both.  I'm deploying to US East 2

**Comment by bjonescts** [comment] 2022-09-26 19:11
https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FKelvinTegelaar%2FCIPP%2Fmain%2Fdeployment%2FAzureDeploymentTemplate.json

To be more precise.

**Comment by KelvinTegelaar** [comment] 2022-09-26 19:14
Not a bug, just ran a successful deployment using both deployment wizards. Check if you've set your token permissions right, and that you are replacing the fork URLs with your own forks.

This is also not the place for issues so we're closing this, you can try to get community support in our discord at https://discord.gg/cyberdrain

**Closed by KelvinTegelaar** 2022-09-26 19:14 UTC
Labels: bug, unconfirmed-by-user

**Comment by samk-acw** [comment] 2022-09-27 07:22
I'm getting the same issue, never deployed before, and confirmed inputs and token permissions are correct. 
For whatever reason this resource property isn't being set. I assume anyone who's deployed before wouldn't have this issue since the property has been set before.

![image](https://user-images.githubusercontent.com/55128650/192458783-0f587256-9930-4834-a814-295ae0b671a6.png)

I set the property manually with `Set-AzResource -PropertyObject @{token=$github_pat} -ResourceId /providers/Microsoft.Web/sourcecontrols/GitHub` and the deployment worked

**Comment by bjonescts** [comment] 2022-09-27 12:23
samk-acw, you're amazing.. this worked perfectly for me!   Thank you so much!
