### ISSUE TITLE
BUG: Error loading group data

### ISSUE THREAD

**Issue by KasMichta** [KelvinTegelaar/CIPP#1022] opened 2022-07-13 18:17 UTC
Shortly after set up, connected to SAM application manually and cleared token cache. Tested permissions, all good. Seems that everything is loading in correctly apart from Groups under Identity Management. When attempting to access this for any tenant, this error occurs:

```
{
  "status": 403,
  "data": [
    "The identity of the calling application could not be established."
  ],
  "message": "Request failed with status code 403"
}
```

**Comment by KelvinTegelaar** [comment] 2022-07-13 18:18
Are you using GDAP? There currently is an issue with GDAP and some of the preapproved applications. The GDAP team is aware of this.

**Comment by KasMichta** [comment] 2022-07-14 07:18
Yes, using GDAP, thanks for the quick response.

**Comment by KasMichta** [comment] 2022-07-14 13:39
Hi again, checked again and realised that no we are not using GDAP. Just using the per-user permissions in partner center. Both the account that I am using to access CIPP and the service account that was used to create the SAM application have admin agent permissions in Partner Center.

**Comment by KasMichta** [comment] 2022-07-14 13:42
The issue also appears when attempting to edit a Team, listing them works fine, however editing them results in the same type of error: 
![image](https://user-images.githubusercontent.com/33022848/178996279-110792e4-4a95-4e8f-967f-33416880b79e.png)

**Comment by KelvinTegelaar** [comment] 2022-07-14 13:48
Sorry, but issues with your SAM setup are not a bug, I'm closing this. Most likely there are missing permissions on your SAM, check the docs at https://cipp.app/docs/user/gettingstarted/permissions/#permissions

**Closed by KelvinTegelaar** 2022-07-14 13:48 UTC
Labels: unconfirmed-by-user

**Comment by KasMichta** [comment] 2022-07-15 09:38
Hi Kelvin, I've reviewed the permissions on the SAM and they match the requirements in the documentation. Is there anything else that could cause these errors?
