### ISSUE TITLE
Offboarding Wizard Times Out

### ISSUE THREAD

**Issue by Da180DegreesIT** [KelvinTegelaar/CIPP#1201] opened 2022-11-07 22:41 UTC
### Description

More of a bug I suppose with the offboarding wizard, it quite often times out on the first attempt, running the second attempt succeeds but fails to do some steps as it already completed those steps the first time (obviously)

1. Select Offboarding Wizard & Choose a Tenant & User
2. Select, Revoke All Sessions, Remove all mobile devices, remove all rules, remove licenses, convert to shared mailbox, disable sign in, reset password, remove from all groups. Set Give another user access to mailbox with automapping. Select Next.

This will intially run through the wizard, and then time out with a time out error. Running the same wizard again succeeds, but with some steps already completed.

I've done this twice in past week and same occured.

I guess this could be fixed by adding some form of timer/pause?

### Environment data

```PowerShell
Azure Enviroment using the One Click Setup :)
```

**Comment by Da180DegreesIT** [comment] 2022-11-07 22:46
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug

**Comment by Da180DegreesIT** [comment] 2022-11-07 22:47
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment] 2022-11-09 14:29
Not a bug, you most likely didn't deploy to the location nearest to you., or haven't followed all instructions for deployments.

We're also closing this as incomplete "Hosted in Azure" tells us nothing. Everything is hosted in Azure. The docs explicitly ask for version numbers, if you have sponsorship, etc. as this information is important. Please do not create bugs when you require support but start a sponsorship.

**Closed by KelvinTegelaar** 2022-11-09 14:29 UTC
Labels: bug, unconfirmed-by-user
