### ISSUE TITLE
Getting error when deploying CA policy template

### ISSUE THREAD

**Issue by JeroenB-Tredion** [KelvinTegelaar/CIPP#1209] opened 2022-11-09 13:57 UTC
### Description

We're getting a error when trying to deploy 2 of our conditional access policies. 
<img width="759" alt="image" src="https://user-images.githubusercontent.com/103125142/200843823-ce8470b1-6dbf-4447-afda-b7b695efadc9.png">

It seems that the API has some problems with deploying. These CA policies did seem to work a week or so ago. 

We also experience a error when deleting a CA policy from the templates. See screenshot for the error.
<img width="743" alt="image" src="https://user-images.githubusercontent.com/103125142/200844541-8f8aeb8b-abf5-45dd-a0e2-ac5c04a537e6.png">

We remade the template by exporting it from a tenant. We also cleared the cache but still the same errors.

### Environment data

```PowerShell
Hosted in Azure
```

**Comment by JeroenB-Tredion** [comment] 2022-11-09 14:00
I confirm that I have checked the documentation thoroughly and believe this to be an actual bug.

**Comment by KelvinTegelaar** [comment] 2022-11-09 14:25
This is not a bug but user error. Your template is incorrectly formatted and most likely includes references to other policies or objects that don't exist.

We're also closing this as incomplete "Hosted in Azure" tells us nothing. Everything is hosted in Azure. The docs explicitly ask for version numbers, if you have sponsorship, etc.  as this information is important. Please do not create bugs when you require support but start a sponsorship.

**Closed by KelvinTegelaar** 2022-11-09 14:25 UTC
Labels: bug, unconfirmed-by-user
