### ISSUE TITLE
FEATURE REQUEST: Add Phishing Policies in to CIPP

### ISSUE THREAD

**Issue by gavsto** [KelvinTegelaar/CIPP#232] opened 2021-11-12 13:20 UTC
**Is your feature request related to a problem? Please describe.**
Add phishing policies in to CIPP

**Describe the solution you'd like**
To be able to see phishing policies for a tenant, and ideally all phishing policies at once

**Comment by KelvinTegelaar** [comment] 2021-11-12 16:02
Duplicate of the spamfilter request maybe?

**Comment by KelvinTegelaar** [comment] 2021-11-19 11:50
Added in Dev

**Closed by KelvinTegelaar** 2021-11-19 11:50 UTC
Labels: enhancement
