### ISSUE TITLE
BUG: Tenant Standards Still Apply after client removed

### ISSUE THREAD

**Issue by vitmsadmin** [KelvinTegelaar/CIPP#951] opened 2022-06-01 03:12 UTC
**Describe the bug**
Applied Tenant Standards for MFA to client but it forced accounts that are not needing to be MFA to have the policy applied.  We reran the Standard without MFA and set the user account MFA to disable. But every 3 hours it is still applying a standard even thought the tenant is not visible in standards and manually we have disabled MFA

**To Reproduce**

1. Go to 'Tenant Standards and set MFA
2. Click on 'Rerun without MFA and manually disable MFA in Azure
3. Refresh azure after 3 hr and MFA has been set to enabled again
4. Error: How to stop the schedule policy for a particular tenant after it has run once.

**Expected behavior**
If the tenant has been removed from the Tenant Standards, it should NOT rerun the policy every 3 hrs

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by KelvinTegelaar** [comment] 2022-06-01 07:22
When you remove a standard from the standards list, and it no longer shows up, it will not apply.

There is a caveat there; if you restart your function app regularly, which you should never  have a reason to do, the previous queue of tasks get re-queued, meaning that they'll apply again because they got queued with older information. 

If this is the case, try the following to fix it;

- Go to the Azure Resource Group
- click on Storage
- click on Storage Explorer
- Click on Tables
- Click on cippxxxxInstances
- Filter on "RuntimeStatus != Completed"
- Delete all jobs that are "Pending" or "running"


This normally should not be required, but I've seen people restart their Function app "because it makes it go faster". This actually breaks a lot more stuff. 

We're closing this as "not a bug".

**Closed by KelvinTegelaar** 2022-06-01 07:22 UTC
Labels: unconfirmed-by-user
