### ISSUE TITLE
BUG: Deleting a tenant from "Excluded Tenant List"

### ISSUE THREAD

**Issue by rthenter1212** [KelvinTegelaar/CIPP#648] opened 2022-01-19 00:12 UTC
**Describe the bug**
When deleting a tenant from the "Excluded Tenant List".  The deleted tenant never shows up in the tenant drop down on any other page.  Even after clearing the cache in settings general page.  . 

**Expected behavior**
Expect the tenant to be including on the tenant selection drop down on other pages after its been removed from excluded tenant list.  

- OS: Windows 11 21H2
- Browser Chrome 
- Version 97.0.4692.71

**Comment by gavsto** [comment] 2022-01-19 11:46
Bug has been confirmed. Initial testing shows it is removing from ExcludedTenants. Not done any further investigation yet.

**Comment by gavsto** [comment] 2022-01-19 15:23
Further testing indicates this is due to the state not being updated on the front-end. Two things need to be done to fix this:

- We need to ensure when an excluded tenant is added or remove we add a hook to clear the tenant state
- We need the clear cache button available in settings to also clear the entire local state

**Comment by KelvinTegelaar** [comment] 2022-01-19 16:27
added localstorage clear to the clearcache button

**Comment by KelvinTegelaar** [comment] 2022-01-19 16:31
excluded tenant seems to no longer have issues now. Fixed in dev.

**Closed by KelvinTegelaar** 2022-01-19 16:31 UTC
Labels: bug, unconfirmed-by-user

**Comment by rthenter1212** [comment] 2022-01-19 18:52
Thanks your work around worked.
