### ISSUE TITLE
Errors while loading / performance issues

### ISSUE THREAD

**Issue by markkoele** [KelvinTegelaar/CIPP#1064] opened 2022-08-10 10:10 UTC
### Description

Every time when i load Cipp for the first time, it will take al lot of time to load all tenants. And every time i'll get an error "The Azure Function has taken too long to respond. Try selecting a different report or a single tenant instead"

![image](https://user-images.githubusercontent.com/72648536/183875682-ecd5bd79-ed4e-4745-a70d-6228dfc0abbe.png)

If i wait a few minutes it will load and it's possible to select a tenant

![image](https://user-images.githubusercontent.com/72648536/183876209-35b1d3c6-a870-4055-ad99-bf5d68ef803d.png)

### Environment data

```PowerShell
Hosting in own azure tenant and deployed with de automatic deployment.
the Frontend and Backend are up to date
```

**Comment by knightian** [comment] 2022-08-10 10:26
Known, this is due to the API being built in Powershell and running as an Azure Function app. When you don't make any API calls for a while, the function app kind of deallocates itself and then when you come back in a few days and send the first API call it "wakes up" and responds again, but it takes some time. We call this a "cold start" so what you are experiencing is not so much a bug, it's a byproduct of using an Azure Functioln app as an API.

**Comment by KelvinTegelaar** [comment] 2022-08-10 10:32
That being said, this should not happen that often.  I'm not seeing the alerts in your screenshot which tell you to use .NET4 and PowerShell 7.2. Make sure you've enabled those, also make sure you've migrated to storagev1 or redeploy.

As this is not a bug, closing the issue.

**Closed by KelvinTegelaar** 2022-08-10 10:32 UTC
Labels: bug, unconfirmed-by-user
