### ISSUE TITLE
Disable/Enable Automapping for a Shared Mailbox

### ISSUE THREAD

**Issue by DarrenChap** [KelvinTegelaar/CIPP#250] opened 2021-11-16 21:45 UTC
Not a common request but some users want to have the From address set by default when sending from a shared mailbox.  If the shared mailbox is automapped in Outlook Desktop then the From address for a new email is always the primary mailbox and has to be changed manually (which is the issue as they forget to do this).

In PowerShell these are the commands I run to do this:

Remove-MailboxPermission -Identity $.Identity -User $.User -AccessRights:FullAccess -Confirm:$false
Add-MailboxPermission -Identity $.Identity -User $.User -AccessRights:FullAccess -AutoMapping $false

It would also be handy to see if Automapping was disabled on a specific mailbox although I am not sure if the AutoMapping setting is visible.

Again, not common so no urgency or expectation.

**Comment by dsghi** [comment] 2021-11-17 20:09
I believe this request is a duplicate of #205

**Comment by KelvinTegelaar** [comment] 2021-11-17 20:16
Yes, closing as duplicate.

**Closed by KelvinTegelaar** 2021-11-17 20:16 UTC
